# Generated by Django 4.1.6 on 2024-02-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traductor", "0002_task_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="image",
        ),
    ]
